#:kivy 2.0
#:import utils kivy.utils

# A CameraScreen não tem UI própria —
# ela abre a câmera nativa do dispositivo via plyer (on_enter em camera.py)
# e redireciona para PreviewScreen após a captura.

<CameraScreen>:
    FloatLayout:

        # Mensagem enquanto câmera nativa carrega
        Label:
            text: "Abrindo câmera..."
            font_size: "15sp"
            color: utils.get_color_from_hex("#FF6B00")
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
